### ISSUE TITLE
Static account number on line 127 of init.sh

### ISSUE THREAD

**Issue by mcassaniti** [danilop/LambdAuth#1]
I think the description should cover this one.

**Comment by danilop** [comment]
Good catch! I fix that using the environmental variable, please give me your feedback if the init.sh script works for you, as you could see I didn't test it in other accounts.

**Comment by jeremiahpslewis** [comment]
Hey! Not sure if this is an obvious error, but when I run init.sh, I get the following error: `rm: edit/*: No such file or directory`.

**Comment by danilop** [comment]
Well, I could have done something better, and maybe I'll improve on that, but the first time it is ok to not have that directory.

**Comment by danilop** [comment]
I added a check if the directory exists before deleting, if it doesn't exists the "edit" directory is created. I needed an empty directory, but that is not "preserved" by Git.

**Comment by jeremiahpslewis** [comment]
Sweet. That helps. I keep on getting `"Missing credentials in config"` on the sign up page, when I build the app...have you tried to build this project using an independent AWS account to check reproducibility?

**Comment by danilop** [comment]
Tried today and when we went over the issues in the init.sh script it
worked.
Here's a few checks:
1. Can you try to reload the page before trying again?
2. Which region are you using?
3. Do you have a well  configured Cognito Identity pool?
4. If you get in the web console of Cognito and select the identity pool,
does it ask to "fix the roles"?

**Comment by danilop** [comment]
I found the issue, thanks, you can fix it running again the init.sh script. There were still hard-coded credentials in one step, sorry.
