### ISSUE TITLE
Error Parsing Parameter '--zip-file': Unable to locate paramfile fileb://...

### ISSUE THREAD

**Issue by JBaczuk** [danilop/LambdAuth#13]
When running init.sh I repeatedly get these errors for every folder in the main folder:

Error parsing parameter '--zip-file': Unable to load paramfile fileb://LambdAuth
VerifyUser.zip.zip: [Errno 2] No such file or directory: u'LambdAuthVerifyUser.z
ip.zip'
Creating function LambdAuthVerifyUser.zip end
F:[mydirectory]\LambdAuth-master\LambdAuth-master\init.sh: line 144: ./deploy.sh: No such file or directory

I've tried running it in Windows 7 and Ubuntu 12.04 LTS

**Comment by JBaczuk** [comment]
I thought the script could only be run in Linux, but the same error happens in Linux as well.

**Comment by danilop** [comment]
It should work on OS X (tested) and Linux (untested). Let me look into that.

**Comment by JBaczuk** [comment]
Ok the .sh script does work on a Mac, but trying to create a user through the browser is not working.  I'll see if I can debug why.

**Comment by ravaan** [comment]
Getting the same error while creating a lambda function in Ubuntu 14.04 - any leads?

**Comment by TomPyle** [comment]
MAYBE excess leftover zip files in path, yielding attempts to create *.zip.zip ?  [ when running init.sh "repeatedly" without completing deploy.sh or cleanup.sh  normally? ]       Note that delete of  temporary lambda zip  is expected in deploy.sh  at line 43
     37   echo "Updating function $f begin..."
     38         cp config.json $f/
     39   cd $f
     40   zip -r $f.zip index.js config.json
     41   aws lambda update-function-code --function-name ${f} --zip-file fileb://${f}.zip --region $REGION
     42         rm config.json
     43         rm $f.zip
     44   cd ..

**Comment by ravaan** [comment]
Hey! thanks for the help! but I got my mistake, made a silly mistake in giving the path.

**Comment by array-addu** [comment]
try it with files:/// prefix
