### ISSUE TITLE
EACCES, permission denied

### ISSUE THREAD

**Issue by JBaczuk** [danilop/LambdAuth#14]
I get the following error when trying to signup through the browser.  

errorMessage: "EACCES, permission denied '/var/task/index.js'", errorType: "Error", stackTrace: Array[7]}

**Comment by JBaczuk** [comment]
So I don't know if this was necessary, but I added `chmod 777 index.js` to the Create Lambda loop in the script, deleted the lambda functions through the AWS console and ran the script again, and the error is gone.

**Comment by falmanna** [comment]
you saved my life!
