### ISSUE TITLE
4096 iterations of PBKDF2-SHA1 is not enough

### ISSUE THREAD

**Issue by mietek** [danilop/LambdAuth#21]
[Matasano recommends](https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2015/march/enough-with-the-salts-updates-on-secure-password-schemes/) using at least **86000** iterations of PBKDF2-**SHA256** in 2015.

**Comment by mikegchambers** [comment]
+1

Thanks mietek.

And anyone using this code in any serious way needs to know this, know why, and find the place in the code to change this themselves.  If they don't or can't then they should think seriously about getting help from someone who does. :)

**Comment by helloniklas** [comment]
Wouldn't it be better to just replace this with bcrypt.

**Comment by jfaraklit** [comment]
+1

**Comment by danilop** [comment]
The best option would be to use AWS KMS for encrypting/decrypting - I think I opened an issue some time ago, but never had the time to work on it.
