### ISSUE TITLE
Error in storeUser: UnrecognizedClientException: The security token included in the request is invalid.

### ISSUE THREAD

**Issue by blindman2k** [danilop/LambdAuth#3]
Hi,

I had some success today getting this working but then I cleared everything out and reinitialised ... now I get an error executing LambdAuthCreateUser. I have spent way too long trying to work out what is going wrong but it seems that it isn't picking up the correct policy that allows LambdAuthCreateUser to write to the DynamoDB. But I can't see what policies it HAS picked up only what it SHOULD pick up. The policy simulater reports no issues, so it's nothing obvious.

Do you have any thoughts?

```
A.
```

**Comment by danilop** [comment]
Check the IAM role used by the Lambda function (form the Lambda console), is it allowing to PutItem to the table? Is the AWS Account ID correct for you?

**Comment by danilop** [comment]
I think it was an issue now solved (the AWS account was cabled or not replaced in the init.sh procedure). Can you try now, running the init script again (it is designed to be non-destructive) ?

**Comment by blindman2k** [comment]
Hi @danilop, I reorganised everything completely differently and so can't run the new code anymore. I hope my comments were helpful regardless :)
