### ISSUE TITLE
botocore.exceptions.ProfileNotFound

### ISSUE THREAD

**Issue by kashif789us** [danilop/LambdAuth#33]
Hello. I am a beginner is aws. I followed the steps from [https://github.com/danilop/LambdAuth/issues/30](url)

Then followed the main readme but when I run init.sh I get alot of following errors:

raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (null) could not be found

**Comment by chahalpardeep** [comment]
You don't need profile_name in Lambda. Role you assign to lambda (while creating it) should have access to perform the tasks. That means, you can remove the profile_name part from code.
