### ISSUE TITLE
init.sh roles env var obscured by single quotes?

### ISSUE THREAD

**Issue by dougtoppin** [danilop/LambdAuth#5]
On line 96 of init.sh it looks like $AWS_ACCOUNT_ID in roles cannot be replaced because of the single quotes being used.

Should it instead be something like this?

roles="{\"unauthenticated\":\"arn:aws:iam::$AWS_ACCOUNT_ID:role/$unauthRole\",\"authenticated\":\"arn:aws:iam::$AWS_ACCOUNT_ID:role/$authRole\"}"

When I use my modified version I get this echo output.

Roles: {"unauthenticated":"arn:aws:iam::xxx:role/Cognito_LambdAuthUnauth_Role","authenticated":"arn:aws:iam::xxx:role/Cognito_LambdAuthAuth_Role"}

**Comment by danilop** [comment]
You're right, I'll do some tests and fix it, thanks!

**Comment by danilop** [comment]
Just tested in a new account and it worked for me. Closing the issue for now, let me know if it works for you.
